import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useContext, useEffect } from "react";
import styles from "../styles/Home.module.css";
import { AppContext } from "./helpers/helpers";
import AOS from "aos";
import "aos/dist/aos.css";
export default function Home() {
  const { theme } = useContext(AppContext);

  useEffect(() => {
    AOS.init();
    AOS.refresh();
  }, []);
  return (
    <div
      id={theme}
      data-aos="fade-up"
      data-aos-duration="3000"
      className={styles.container}
    >
      {/* <div data-aos="fade-up" data-aos-duration="3000"></div> */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.heading}>
        <h1>Quiz </h1>
        <div className={styles.HeroImg}>
          <img src="./quizImg.svg" alt="img" />
        </div>

        <p>You think you're smart huh? Lets see just how smart you are... </p>
        <Link href="./Profile">
          <button>Begin! </button>
        </Link>
      </div>
    </div>
  );
}
